### ISSUE TITLE
Way too similar to my portfolio

### ISSUE THREAD

**Issue by gavinanthony** [GavinThomas1192/React-Gavin-Thomas-Portfolio#8]
Hey man, just saw your site, https://gthomas.me/

It's ok to take a look at my source code and get inspired by how I built the site. That's why I hosted the code on GitHub.

It's **not** ok to fork the code and copy/paste your name in there. It's not a template or a theme. I hope you weren't planning on doing that. And if you weren't, wait to publish it online until you're ready.

Thanks man

**Comment by GavinThomas1192** [comment]
Hey Gavin, 
Sorry about that, I will take it down right away.
